### ISSUE TITLE
deepFindRule conflict between GamelanPatterns and EventArray quarks

### ISSUE THREAD

**Issue by thresholdpeople** [musikinformatik/GamelanPatterns#1]
Hello,

When installing this quark and recompiling the library I received the following error: 

```
ERROR: Method Tafsiran:deepFindRule already defined.
  in file '~/Library/Application Support/SuperCollider/downloaded-quarks/GamelanPatterns/Classes/Tafsiran.sc'
  line 86 char 13:

  	deepFindRule { arg list, index=0;
               
  		^rules.deepFindRule(list, index)
-----------------------------------
```

Seems that there is a conflict between this and a method of the same name in the EventArray quark.

**Comment by telephon** [comment]
Thanks for reporting, I'll take a look.

**Comment by telephon** [comment]
Ah that was easy to fix, really just a duplicate method – I have no clue how this got in. Can you check again?

**Comment by thresholdpeople** [comment]
that fixed it! thank you!
